/*
 * SVGHMI logic-side data.
 *
 * In split (hot-swap) builds svghmi.c is compiled into the IOs .so, but the PLC
 * program instances it observes are defined in the logic .so.  This companion file
 * is compiled into the logic .so; it statically instantiates the HMI item array
 * (whose &(cpath) initializers resolve against those program instances) plus the
 * read/write/send buffers, the tree fingerprint and the geometry constants, and
 * exports them.  svghmi.c resolves these symbols at load / hot-swap and works
 * entirely through pointers, so it stays independent of HMI content.
 *
 * Generated by Beremiz - do not edit.
 */

#include "iec_types_all.h"
#include "accessor.h"
#include "POUS.h"
#include "config.h"
#include "beremiz.h"
#include "svghmi.h"

%(extern_variables_declarations)s

const unsigned int svghmi_item_count      = %(item_count)d;
const unsigned int svghmi_buffer_size     = %(buffer_size)d;
const unsigned int svghmi_max_connections = %(max_connections)d;
const unsigned int svghmi_heartbeat_index = %(heartbeat_index)d;

const uint8_t svghmi_hmi_hash[HMI_HASH_SIZE] = {%(hmi_hash_ints)s};

/* PLC reads from rbuf / writes to wbuf; sbuf is the worst-case send buffer. */
char svghmi_rbuf[%(buffer_size)d];
char svghmi_wbuf[%(buffer_size)d];
char svghmi_sbuf[HMI_HASH_SIZE + %(buffer_size)d + %(item_count)d * sizeof(uint32_t)];
const unsigned int svghmi_sbuf_size = sizeof(svghmi_sbuf);

hmi_tree_item_t svghmi_hmi_tree_items[] = {
%(variable_decl_array)s
};
