/*
 * SVGHMI logic-side address table.
 *
 * In split (hot-swap) builds svghmi.c is compiled into the IOs .so, but the PLC
 * program instances it observes are defined in the logic .so (loaded afterwards).
 * This companion file is compiled into the logic .so and exports svghmi_ptr_table,
 * the addresses of every HMI variable in the same order as svghmi.c's
 * hmi_tree_items[].  svghmi.c resolves this table at runtime (__logic_bound_svghmi)
 * and rebinds its item pointers after each logic load / hot-swap (__logic_active_svghmi).
 *
 * Generated by Beremiz - do not edit.
 */

#include "iec_types_all.h"
#include "accessor.h"
#include "POUS.h"
#include "config.h"
#include "beremiz.h"

%(extern_variables_declarations)s

void * const svghmi_ptr_table[] = {
%(ptr_table_array)s
};
