/**
 * Shim for the PLC logic shared object.
 *
 * Provides a stable entry point (plc_logic_cycle) wrapping config_run__
 * and debug publishing, called via function pointer from the IOs .so.
 *
 * Also provides __init_PLCLogic / __cleanup_PLCLogic used by PLCObject.py
 * to initialize and clean up the logic instance tree.
 **/

#include "beremiz.h"

/*
 * Prototypes of PLC logic functions (generated by matiec)
 **/
void config_run__(unsigned int tick);
void config_init__(void);

/*
 * Debug
 **/
#ifndef PLC_NO_DEBUG
int  __init_debug(void);
void __cleanup_debug(void);
void __publish_debug(void);
#endif

char *PLC_ID_LOGIC = 0;

/*
 * plc_logic_cycle — single entry point called by IOs .so on every PLC cycle.
 * Runs the IEC program and collects debug data.
 **/
void plc_logic_cycle(unsigned int tick)
{
    config_run__(tick);
#ifndef PLC_NO_DEBUG
    __publish_debug();
#endif
}

/*
 * __init_PLCLogic — initialize PLC logic instance tree and debug.
 * Called from PLCObject.py (Python main thread) via loadPLCLogic().
 **/
int __init_PLCLogic(int argc, char **argv)
{
    config_init__();
#ifndef PLC_NO_DEBUG
    return __init_debug();
#else
    return 0;
#endif
}

/*
 * __cleanup_PLCLogic — cleanup PLC logic debug state.
 * Called from PLCObject.py after the IOs .so PLC thread has stopped.
 **/
void __cleanup_PLCLogic(void)
{
#ifndef PLC_NO_DEBUG
    __cleanup_debug();
#endif
}
